### PR TITLE
Fix scoping for method calls, added exception handler around include to limit errors to that file

### PR DESCRIPTION
**Pull request by jthomaskerr**
I've made some improvements, if you have any stylistic or other concerns please let me know and i'll amend the request.

### CODE REVIEW

**Comment by colder** [comment]
Thanks for this! I have taken a quick look and it looks fine so far.

I will review the patch more thoroughly and apply it as soon as possible.

Best,

**Comment by colder** [comment]
Hi,

something I don't understand is why you decided to carry namespaces past ASTs, is it for reporting purposes? Because now you have to deal with them at every phases, instead of just translating during one.

For instance, you could resolve all namespaces using one phase doing ASTTransform. And then simply make sure that there is no longer any occurence of namespace define/use.

**Comment by jthomaskerr** [comment]
I did consider this. It looked to me as if the STToAST conversion was
purely syntactical, and that things like interpreting context of symbols
was left to a later stage.

Judging by your comment this is not quite accurate. We could resolve all
namespace and use statements into symbol names in this first step; i wonder
though if there are any cases where this is not desirable.

Regards,
Joe.

**Comment by colder** [comment]
STToAST is almost entirely syntactical, you are right, it is just transforming the syntax trees into ASTs.

Since namespaces are purely syntactical as well, it could be done during STToAST, but it wouldn't be ideal.

What I had in mind is a phase after STToAST and before others, transforming one AST using namespaces to an AST without namespaces, using i.e. ASTTransform.

I will try to implement namespaces that way this afternoon. From the above patch, it seems you did more than just implement namespaces, can you elaborate on what you fixed apart from that?

Best,

**Comment by colder** [comment]
I'm in the process of fixing few issues, upgrading to sbt 0.12, add some automated tests, and implement namespaces in the way I described earlier, things will be unstable for a while but Phantm should fall back on its feet in a few days at most.

I was wondering if you could give me some details on your usage experience of Phantm, how do you use it, in what kind of codebase, did you have good results with it?

Best,

**Comment by jthomaskerr** [comment]
I  did fix a few other minor bugs - these i detailed in separate commits - wrap exceptions in include files so that other files may continue to be parsed, and specify the class scope in TypeAnalyzingPhase so that visibility is calculated correctly. I think thats all I've done so far apart from namespaces.

I'm also planning to implement static::

**Comment by jthomaskerr** [comment]
I'm hoping to use phantm as an addition to lint when building in my ide and also as part of maven. I'm not sure yet whether this will be feasible or too noisy. I suspect that more granularity could be added to the verbosity settings.

**Comment by colder** [comment]
Hi,

I fixed a lot of different things in the process, performed many cleanups. Namespaces should now be implemented in the way I described, as a specific phase called NamespacesResolver, both kinds of namespaces are supported, and all possible usages should be handled.

I may have not included the other parts you fixed, given that now your PR would probably not merge gracefully. Feel free to resubmit a PR addressing the other issues and I will be happy to merge them.

Best

**Comment by colder** [comment]
Closing this.

**Pull request closed without merging**
